name: Run unit tests

on:
  - push
  - pull_request

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.7"]

    steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Checkout
      uses: actions/checkout@v2

    - name: Bundle install
      run: bundle install

    - name: Run tests
      run: COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }} rspec -I . app_spec.rb